spring.application.name=Employee-Management
server.port=8081
#spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
#spring.datasource.username=postgres
#spring.datasource.password=root
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update

# ✅ Reactive DB config (R2DBC)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/employee_management
spring.r2dbc.username=postgres
spring.r2dbc.password=root

# Optional
spring.sql.init.mode=always